version: 2
jobs:
  lint:
    docker:
      - image: circleci/openjdk:8-jdk
     steps:
      - checkout
      - run:
          name: checkstyle
          command: |
            cd simulation
            mvn checkstyle:checkstyle
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: mvn compile
          command: |
            cd simulation
            mvn compile

workflow:
  version: 2
  build-lint:
    jobs:
      - build
      - lint
