version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: mvn compile
          command: |
            cd simulation
            mvn compile

workflow:
  version: 2
  build:
    jobs:
      - build
